### 1. 해결한 문제 저장 (POST)
POST {{host}}/api/solved
Content-Type: application/json

{
  "userId": "juheon",
  "problemNumber": 1000,
  "solvedAt": "2026-02-16T15:00:00.000Z"
}

### 2. 전체 해결 목록 조회 (GET)
GET {{host}}/api/solved
Accept: application/json

### 3. 특정 유저의 해결 목록 조회 (GET)
GET {{host}}/api/solved?userId=juheon
Accept: application/json